-- Dash-OS Phase 2A — Reporter file generation registry
-- Tracks every file generated by the Reporter agent (PDF/PPTX/CSV/XLSX/DOCX/JSON/MD).
-- Files live on disk under /app/knowledge/generated/{project_slug or '_global'}/{file_id}.{ext}.
-- Background sweeper deletes expired rows + disk files every hour.

CREATE TABLE IF NOT EXISTS dash.dash_generated_files (
  id TEXT PRIMARY KEY,                  -- 'gen_<8hex>'
  project_slug TEXT,
  user_id INTEGER,
  agent_name TEXT,
  run_id TEXT,
  file_type TEXT NOT NULL,              -- 'pdf' | 'pptx' | 'csv' | 'xlsx' | 'docx' | 'json' | 'md'
  filename TEXT NOT NULL,
  storage_path TEXT NOT NULL,           -- absolute path on container (volume-mounted)
  size_bytes BIGINT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ DEFAULT now() + INTERVAL '7 days'
);

CREATE INDEX IF NOT EXISTS idx_genfile_project
  ON dash.dash_generated_files(project_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_genfile_expires
  ON dash.dash_generated_files(expires_at);
