apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dash-knowledge-data
  labels:
    {{- include "dash.labels" . | nindent 4 }}
    component: storage
spec:
  accessModes:
    - {{ .Values.storage.knowledge.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.knowledge.size }}
  {{- if .Values.storage.knowledge.storageClassName }}
  storageClassName: {{ .Values.storage.knowledge.storageClassName | quote }}
  {{- end }}
