"""End-to-end test harness for the edge-case fixture zoo.

Single parametrized test that walks every CSV in tests/fixtures/edge_cases/
through the full upload → retrain → poll → verify pipeline.

Skipped automatically when the container isn't reachable (handled by
conftest.py's container probe).

Run via:
    make test-edge-cases
or:
    pytest tests/test_e2e.py -v --tb=short -m e2e
"""
from __future__ import annotations

import glob
import os
import time

import pytest

# Collect fixtures relative to this file so the suite works from any cwd.
_FIXTURES_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "fixtures",
    "edge_cases",
)
EDGE_CASES = sorted(glob.glob(os.path.join(_FIXTURES_DIR, "*.csv")))


@pytest.mark.parametrize(
    "fixture",
    EDGE_CASES,
    ids=lambda f: os.path.basename(f),
)
@pytest.mark.e2e
def test_full_pipeline(fixture, http_client, api_base, temp_project_slug):
    """Run a single fixture through the entire upload → train → verify path.

    Acceptance contract per fixture:
      1. Upload must return 200 (or 400 for fixtures that are intentionally
         malformed — only `empty.csv` qualifies by default).
      2. POST /retrain must return 200.
      3. Within 5 minutes the latest training run must reach status='done'.
      4. /memories must report ≥ 1 memory after training (signal that the
         knowledge layers populated).
    """
    slug = temp_project_slug
    fname = os.path.basename(fixture)

    # 1. Upload via multipart -F project=
    with open(fixture, "rb") as f:
        r = http_client.post(
            f"{api_base}/upload",
            files={"file": (fname, f, "text/csv")},
            data={"project": slug},
            timeout=120.0,
        )
        # Option A: empty.csv is EXPECTED to reject with 400 or 422. Others must succeed.
        if "empty" in fname.lower():
            assert r.status_code in (400, 422), (
                f"empty fixture {fname} should reject with 400/422, got {r.status_code}"
            )
            return  # expected reject path — success
        assert r.status_code == 200, (
            f"upload failed for {fname}: {r.status_code} {r.text[:300]}"
        )

    # 2. Kick off retrain
    r = http_client.post(
        f"{api_base}/projects/{slug}/retrain",
        timeout=30.0,
    )
    assert r.status_code == 200, (
        f"retrain start failed for {fname}: {r.status_code} {r.text[:300]}"
    )

    # 3. Poll training run for up to 5 minutes (60 × 5s).
    last_status = None
    last_run = None
    for _ in range(60):
        time.sleep(5)
        r = http_client.get(
            f"{api_base}/projects/{slug}/training-runs?limit=1",
            timeout=15.0,
        )
        if r.status_code != 200:
            continue
        body = r.json()
        # Endpoint may return a bare list OR a dict wrapping it.
        runs = body if isinstance(body, list) else body.get("runs") or body.get("training_runs") or []
        if not runs:
            continue
        last_run = runs[0]
        last_status = last_run.get("status")
        if last_status in ("done", "failed"):
            break

    assert last_run is not None, (
        f"no training run row appeared for {fname} within 5 minutes"
    )
    assert last_status == "done", (
        f"training did not reach 'done' for {fname}: "
        f"status={last_status} error={last_run.get('error')}"
    )

    # 4. Verify at least one memory was written.
    r = http_client.get(
        f"{api_base}/projects/{slug}/memories",
        timeout=15.0,
    )
    assert r.status_code == 200, (
        f"memories endpoint failed for {fname}: {r.status_code} {r.text[:200]}"
    )
    body = r.json()
    memories = body.get("memories") if isinstance(body, dict) else body
    memories = memories or []
    assert len(memories) >= 1, (
        f"no memories were populated for {fname} after training"
    )


# ---------------------------------------------------------------------------
# Nightly million-row scale test (NOT parametrized; only runs when
# tests/fixtures/edge_cases/million_row.csv exists and is > 50MB).
# Generated by tests/fixtures/edge_cases/gen_million.py — gitignored.
# ---------------------------------------------------------------------------

@pytest.mark.e2e
def test_million_row_scale(http_client, api_base, temp_project_slug):
    """Upload a true 1M-row CSV and assert the hot paths handle real scale.

    Skipped unless the million_row.csv fixture is present (>50MB). Generate via:
        python tests/fixtures/edge_cases/gen_million.py

    Assertions:
      - upload completes in < 120s
      - training reaches 'done' within 20 minutes
      - >= 1 memory + >= 1 training_qa row after training
    """
    fixture = os.path.join(_FIXTURES_DIR, "million_row.csv")
    if not os.path.exists(fixture):
        pytest.skip("million_row.csv not present — run gen_million.py to generate")
    size_mb = os.path.getsize(fixture) / (1024 * 1024)
    if size_mb < 40:
        pytest.skip(
            f"million_row.csv only {size_mb:.1f}MB — expected >40MB; regenerate"
        )

    slug = temp_project_slug
    fname = "million_row.csv"

    # 1. Upload, time it, assert < 120s
    t0 = time.time()
    with open(fixture, "rb") as f:
        r = http_client.post(
            f"{api_base}/upload",
            files={"file": (fname, f, "text/csv")},
            data={"project": slug},
            timeout=240.0,
        )
    upload_s = time.time() - t0
    assert r.status_code == 200, (
        f"million-row upload failed: {r.status_code} {r.text[:300]}"
    )
    assert upload_s < 120.0, (
        f"million-row upload took {upload_s:.1f}s — expected <120s"
    )

    # 2. Trigger retrain
    r = http_client.post(
        f"{api_base}/projects/{slug}/retrain",
        timeout=60.0,
    )
    assert r.status_code == 200, (
        f"million-row retrain start failed: {r.status_code} {r.text[:300]}"
    )

    # 3. Poll training run for up to 20 minutes (240 × 5s)
    last_status = None
    last_run = None
    for _ in range(240):
        time.sleep(5)
        r = http_client.get(
            f"{api_base}/projects/{slug}/training-runs?limit=1",
            timeout=30.0,
        )
        if r.status_code != 200:
            continue
        body = r.json()
        runs = body if isinstance(body, list) else body.get("runs") or body.get("training_runs") or []
        if not runs:
            continue
        last_run = runs[0]
        last_status = last_run.get("status")
        if last_status in ("done", "failed"):
            break

    assert last_run is not None, "no training run row appeared within 20 minutes"
    assert last_status == "done", (
        f"million-row training did not reach 'done': "
        f"status={last_status} error={last_run.get('error')}"
    )

    # 4. Verify memories >= 1
    r = http_client.get(
        f"{api_base}/projects/{slug}/memories",
        timeout=30.0,
    )
    assert r.status_code == 200, (
        f"memories endpoint failed: {r.status_code} {r.text[:200]}"
    )
    body = r.json()
    memories = body.get("memories") if isinstance(body, dict) else body
    memories = memories or []
    assert len(memories) >= 1, "no memories populated after million-row training"

    # 5. Verify training_qa >= 1
    r = http_client.get(
        f"{api_base}/projects/{slug}/training-qa",
        timeout=30.0,
    )
    if r.status_code == 200:
        body = r.json()
        qa = body.get("training_qa") if isinstance(body, dict) else body
        qa = qa or []
        assert len(qa) >= 1, "no training_qa rows populated after million-row training"
